Update v2raymanager

diff --git a/Modulos/v2raymanager b/Modulos/v2raymanager
--- a/Modulos/v2raymanager
+++ b/Modulos/v2raymanager
@@ -48,7 +48,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     intallv2ray () {
     apt install python3-pip -y 
     source <(curl -sL https://raw.githubusercontent.com/ConfigMods/SSHPLUS/main/Modulos/v2ray)
-    echo -e "\033[1;37m\033[1;33mIntalado com Exito!\033[1;31m"
+    echo -e "\033[1;37m\033[1;33mIntalado con Exito!\033[1;31m"
     USRdatabase="/etc/SSHPlus/RegV2ray"
     [[ ! -e ${USRdatabase} ]] && touch ${USRdatabase}
     sort ${USRdatabase} | uniq > ${USRdatabase}tmp
@@ -60,7 +60,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
 
     protocolv2ray () {
     echo -e "\E[44;1;37m            ALTERAR PROTOCOLO V2RAY             \E[0m"
-    echo -e "\033[1;37m• \033[1;33mEscolha a opção 3 e coloque o domínio do seu IP\033[1;31m"
+    echo -e "\033[1;37m• \033[1;33mElige la opción 3 y pon tu IP de dominio\033[1;31m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     v2ray stream
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
@@ -69,14 +69,14 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     }
     tls () {
     clear
-    echo -e "\E[44;1;37m            Ativar ou Desativar TLS             \E[0m"
+    echo -e "\E[44;1;37m            Activar o Desactivar TLS             \E[0m"
     v2ray tls
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
     fun_v2raymanager
     }
     portv () {
-    echo -e "\E[44;1;37m            ALTERAR PORTA V2RAY             \E[0m"
+    echo -e "\E[44;1;37m            ALTERAR PUERTO V2RAY             \E[0m"
     v2ray port
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
@@ -92,13 +92,13 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     unistallv2 () {
     source <(curl -sL https://raw.githubusercontent.com/ConfigMods/SSHPLUS/main/Modulos/v2ray) --remove > /dev/null 2>&1
     rm -rf /etc/SSHPlus/RegV2ray > /dev/null 2>&1
-    echo -e "\n\033[1;32mV2RAY REMOVIDO COM SUCESSO !\033[0m"
+    echo -e "\n\033[1;32mV2RAY REMOVIDO CON EXITO !\033[0m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
     fun_v2raymanager
     }
     infocuenta () {
-    echo -e "\E[44;1;37m            INFORMAÇÃO DE CONTA             \E[0m"
+    echo -e "\E[44;1;37m            INFORMACIÓN DE LA CUENTA             \E[0m"
     v2ray info
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
@@ -120,7 +120,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     sed -i '17i\           \},' /etc/v2ray/config.json
     echo ""
     while true; do
-    echo -ne "\e[91m >> Digite um usuário: \033[1;92m"
+    echo -ne "\e[91m >> Digite un usuqrio: \033[1;92m"
          read -p ": " nick
          nick="$(echo $nick|sed -e 's/[^a-z0-9 -]//ig')"
          if [[ -z $nick ]]; then
@@ -134,7 +134,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     done
     echo -e "\e[91m >> Adicionar UUID: \e[92m$UUID "
     while true; do
-         echo -ne "\e[91m >> Duração de UUID (Dias):\033[1;92m " && read diasuser
+         echo -ne "\e[91m >> Duración de UUID (Dias):\033[1;92m " && read diasuser
          if [[ -z "$diasuser" ]]; then
          echo -e "$msg17" && continue
          elif [[ "$diasuser" != +([0-9]) ]]; then
@@ -197,7 +197,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     v2ray restart > /dev/null 2>&1
     echo ""
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
-    echo -e "\e[92m           UUID ELIMINADO COM EXITO "
+    echo -e "\e[92m           UUID ELIMINADO CON EXITO "
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
     fun_v2raymanager
@@ -217,7 +217,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     local RETURN="$(cat $HOST|cut -d'|' -f2)"
     local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
     if [[ -z $RETURN ]]; then
-    echo -e "----- NENHUM USUARIO REGISTRADO -----"
+    echo -e "----- SIN USUARIO REGISTRADO -----"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
     fun_v2raymanager
     else
@@ -254,7 +254,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     clear 
     clear
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
-    echo -e "\E[44;1;37m            LIMITAR MB X PORT | UUID V2RAY             \E[0m"
+    echo -e "\E[44;1;37m            LIMITAR MB X PUERTO | UUID V2RAY             \E[0m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     ###VER
     estarts () {
@@ -264,7 +264,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     local RETURN="$(cat $HOST|cut -d'|' -f2)"
     local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
     if [[ -z $RETURN ]]; then
-    echo -e "----- NENHUMA PORTA REGISTRADA -----"
+    echo -e "----- SIN PUERTO REGISTRADO -----"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
     fun_v2raymanager
     else
@@ -336,7 +336,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     local RETURN="$(cat $HOST|cut -d'|' -f2)"
     local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
     if [[ -z $RETURN ]]; then
-    echo -e "----- NENHUMA PORTA REGISTRADA -----"
+    echo -e "----- SIN PUERTO REGISTRADA -----"
     return 0
     else
     i=1
@@ -374,7 +374,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     done
     invaliduuid () {
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
-    echo -e "\e[91m                PORTA INVALIDA \n"
+    echo -e "\e[91m                PUERTO INVALIDO \n"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
     fun_v2raymanager
@@ -391,11 +391,11 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     fun_v2raymanager
     }
     ## MENU
-    echo -e "\033[1;37m\033[1;33m[1] > LIMITAR DADOS x PORTA\033[1;31m"
-    echo -e "\033[1;37m\033[1;33m[2] > RESETAR DADOS DE PORTA\033[1;31m"
+    echo -e "\033[1;37m\033[1;33m[1] > LÍMITE DATOS x PUERTO\033[1;31m"
+    echo -e "\033[1;37m\033[1;33m[2] > RESTABLECER DATOS DEL PUERTO\033[1;31m"
     echo -e "\033[1;37m\033[1;33m[3] > VER DATOS CONSUMIDOS\033[1;31m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
-    echo -e "\033[1;32m [0] > \e[97m\033[1;41m VOLTAR \033[1;37m"
+    echo -e "\033[1;32m [0] > \e[97m\033[1;41m VOLVER \033[1;37m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     selection=$(selection_fun 3)
     case ${selection} in
@@ -420,7 +420,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     fi
     unset PID_GEN
     PID_GEN=$(ps x|grep -v grep|grep "limv2ray")
-    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESATIVADO ] " || PID_GEN="\e[92m [ ATIVADO ] "
+    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESACTIVADO ] " || PID_GEN="\e[92m [ ACTIVADO ] "
     statgen="$(echo $PID_GEN)"
     clear 
     clear
@@ -441,7 +441,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     local range
     for((i=0; i<=$1; i++)); do range[$i]="$i "; done
     while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
-    echo -ne "\033[1;37m ► Selecione uma Opção: " >&2
+    echo -ne "\033[1;37m ► Seleccione una opcion: " >&2
     read selection
     tput cuu1 >&2 && tput dl1 >&2
     done
@@ -449,7 +449,7 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
     }
 
     PID_GEN=$(ps x|grep -v grep|grep "limv2ray")
-    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESATIVADO ] " || PID_GEN="\e[92m [ ATIVADO ] "
+    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESACTIVADO ] " || PID_GEN="\e[92m [ ACTIVADO ] "
     statgen="$(echo $PID_GEN)"
     #SPR & 
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
@@ -461,9 +461,9 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
 			echo -e "\E[44;1;37m                GERENCIADOR V2RAY                 \E[0m\n"
 
 			xv2ray1=`if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
-			echo -e "\e[92m ATIVADO"
+			echo -e "\e[92m ACTIVADO"
 			else
-			echo -e "\e[91m DESATIVADO"
+			echo -e "\e[91m DESACTIVADO"
 			fi`;
             echo -e "\033[1;32mSERVICO: \033[1;33mV2RAY \033[1;32m$xv2ray1\033[1;37m" 
 			xv2ray=`if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
@@ -477,11 +477,11 @@ msg17='\033[1;37m\033[1;33m(Sem imformação - Para Cancelar Digite CRTL + C)\03
 [\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mALTERAR PROTOCOLO\033[1;31m
 [\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mACTIVAR TLS\033[1;31m
 [\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mALTERAR PUERTO V2RAY\033[1;31m
-[\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mADICIONAR USUARIO UUID\033[1;31m
+[\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mAGREGAR NUEVO USUARIO UUID\033[1;31m
 [\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mELIMINAR USUARIO UUID\033[1;31m
 [\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mMOSTRAR USUARIOS REGISTRADOS\033[1;31m
 [\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mINFORMACION DE CUENTA\033[1;31m
-[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mESTATÍSTICAS DE CONSUMO\033[1;31m
+[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mESTADISTICAS DE CONSUMO\033[1;31m
 [\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mLIMITADOR POR CONSUMO\e[91m ( BETA x PORT )\033[1;31m
 [\033[1;36m11\033[1;31m] \033[1;37m• \033[1;33mLIMPADOR DE EXPIRADOS ------- $statgen\033[1;31m
 [\033[1;36m12\033[1;31m] \033[1;37m• \033[1;33mDESINSTALAR V2RAY\033[1;31m
